#!/bin/bash

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

case $BLOCK_BUTTON in
	3) notify-send "🔋 Battery module" "🔋: discharging
 : not charging
♻: stagnant charge
: charging
⚡: charged
❗: battery very low!
- Scroll to change adjust xbacklight." ;;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="⚡" ;;
		"Discharging") status=" " ;;
		"Charging") status="" ;;
		"Not charging") status="" ;;
		"Unknown") status="♻️" ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "🔋" ] && [ "$capacity" -le 20 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"

if [ $(cat /sys/class/power_supply/BAT1/status) == "Charging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -gt "95" ]; then
	notify-send "Battery status" "Battery full"
elif [ $(cat /sys/class/power_supply/BAT1/status) != "Charging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -eq "20" ]; then
	notify-send "Battery status" "Battery low"
elif [ $(cat /sys/class/power_supply/BAT1/status) != "Charging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -eq "15" ]; then
	notify-send "Battery status" "Battery low"
elif [ $(cat /sys/class/power_supply/BAT1/status) != "Charging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -eq "13" ]; then
	notify-send "Battery status" "Battery low"
elif [ $(cat /sys/class/power_supply/BAT1/status) != "Charging" ] && [ $(cat /sys/class/power_supply/BAT1/capacity) -eq "10" ]; then
	notify-send "Battery status" "Battery low"
fi
